[project]
name = "guidio"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4>=4.14.3",
    "dotenv>=0.9.9",
    "elevenlabs>=2.36.1",
    "openai>=2.21.0",
    "requests>=2.32.5",
    "tqdm>=4.67.3",
]
